### ISSUE TITLE
TODO: 2018-11-29

### ISSUE THREAD

**Issue by yinleon** [SMAPPNYU/smapp_stance_classifier#2]
Checklist

- [ ] Loading pre-trained weights https://github.com/SMAPPNYU/smapp_stance_sentiment/issues/5
- [x] DataLoader fastai style. #6 
- [x] Get the Cyclical LR to work with existing LM
- [x] ssh keys?
- [ ] Language model to classifier #11 
- [ ] Tests, re-create IMDB example
- [ ] match the model to ulmfit (and re-run the fastai_tests)
- [x] fix the language model sampling function #10
